### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by MissLaia** [WiseHollow/FundamentalsX#8]
Hey,
I'm trying to put permissions with your plugin on my spigot server. Your plugin works with the "operator" obviusly but i'm really confused how can i do that. I never did that, with any other plugin about permissions. Then I will really apreciate if you show me where and how i can put permissions for default players and VIP players for example. I read your separate permissions for every file, but i have no idea how can i put it and how players will get the "default player permissions".

Thanks,
Laia.

**Comment by WiseHollow** [comment]
Hi Laia,

May I ask what permissions plugin you're using? Commands for adding permissions differ from plugin to plugin. 

For general player permissions, adding "Fundamentals.Player" should do you well. There are many individual permissions for each command and feature that you can add as well. 

https://github.com/WiseHollow/FundamentalsX/wiki/Permissions

**Comment by MissLaia** [comment]
Hey WiseHollow,
finally it works. I'm using PermissionsEX. Now I have a problem with the use of "home". The players have issues with it. They only can use one time per session or they got a error message called "internal error ocurred... blablabla". The solution for now is reconnect to the server and they can use it again, but it's a little uncomfortable.

**Comment by WiseHollow** [comment]
Oh goodness. I'll take a look into that as soon as I get home this evening. I'll keep you updated. :)

**Comment by WiseHollow** [comment]
@MissLaia I'm having trouble reproducing this issue. Could you write the exact steps you took to make this happen. Also, could you provide any errors given in the console? Thanks!

**Comment by WiseHollow** [comment]
It hit me that you could be on an old version of Spigot. I remember a bug similar to what you reported that was when using the 1.12.x compatible version. Would I be right to assume you are using 1.12 and not 1.13? @MissLaia

**Comment by WiseHollow** [comment]
Issue has been fixed in FundamentalsX 1.3.0 for Spigot v1.12.2.
